// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtotitaikcbgbjxlvzzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10b3RpdGFpa2NiZ2JqeGx2enpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzEzMjYsImV4cCI6MjA2Mzc0NzMyNn0.Glp-c7bi0tViMNwifoZa8Ri71hTE1_oE7qymfTqixnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);